### ISSUE TITLE
deputy Error signature verification failed

### ISSUE THREAD

**Issue by ScottGold** [bnb-chain/bep3-deputy#13]
I try to swap my erc20 token to bnb chain on testnet.
swap contract: 0xb79faa1a849d8b649db4e0b5eedc896debc6e445
my erc20 token: 0x09E9443B2Ccf44f58E2751D7376f821d7a1Ec360
my bep2 symbol:GGG

**my execute js**:
[swapTokenWithEther.js](https://github.com/ScottGold/open-resource/blob/master/swapTokenWithEther.js)

**my deputy config file**:
[test-config-eth.json](https://github.com/ScottGold/open-resource/blob/master/test_config_eth%20-%20copy.json)

I use deputy from github, last commit is Date:   Thu Jul 23 03:23:45 2020 +0100
**deputy run command**:
./deputy --bnb-network 0 --config-type local --config-path ./test_config_eth.json

**When I finish step2() in swapTokenWithEther.js, deputy throw an error by telegram bot:**

set swap status to BEP2_HTLT_SENT_FAILED other_id=32258ff2a2777b7b5641f58c9a8d8d895cdcfc37822d12de23133f9321284be8 bnb_id=5a6fe1b76d847e98a06ab4bc5b33a539b3175b762f2de24a45f9af6ee29d4e90: got non retryable error from sending htlt: {"codespace":1,"code":4,"abci_code":65540,"message":"signature verification failed"}

**I find another error in deputy output:**
2020-08-14 10:28:05 ERROR GetBlockAndTxs parse tx error, err=unmarshal to tx.StdTx failed after 6 bytes

Pls help me address this error.

**Comment by yutianwu** [comment]
you can test with branch `update_testnet `

**Comment by huangsuyu** [comment]
(node:10510) UnhandledPromiseRejectionWarning: Error: signature verification failed
    at /root/binance-chain/test/node_modules/@binance-chain/javascript-sdk/lib/utils/request.js:69:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async step4 (/root/binance-chain/test/swapTokenWithEther.js:143:15)

**Comment by HaoyangLiu** [comment]
> set swap status to BEP2_HTLT_SENT_FAILED other_id=32258ff2a2777b7b5641f58c9a8d8d895cdcfc37822d12de23133f9321284be8 bnb_id=5a6fe1b76d847e98a06ab4bc5b33a539b3175b762f2de24a45f9af6ee29d4e90: got non retryable error from sending htlt: {"codespace":1,"code":4,"abci_code":65540,"message":"signature verification failed"}

Can you share your tx bytes here?
